name: "Repo: Label Sync"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  issues: write

jobs:
  sync:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels from config
        uses: micnncim/action-label-syncer@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yml
